// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-team.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/data/team.ts
var site = "https://amareacosmetics.it";
var teamMembers = [
  {
    name: "Dott.ssa Anna Manzella",
    slug: "anna-manzella",
    role: "Founder & CEO",
    title: "Dottoranda in Scienze Biomolecolari",
    shortBio: "Specializzata in biologia della pelle e rigenerazione tissutale.",
    email: "anna.manzella@amareacosmetics.it",
    profileUrl: `${site}/team/anna-manzella`
  },
  {
    name: "Dott.ssa Alessia Luccarini",
    slug: "alessia-luccarini",
    role: "Laboratory Research & Development",
    title: "PhD in Scienze Biomolecolari",
    shortBio: "Studio di agenti fotoprotettivi naturali.",
    email: "alessia.luccarini@amareacosmetics.it",
    profileUrl: `${site}/team/alessia-luccarini`
  },
  {
    name: "Dott. Francesco Mengarelli",
    slug: "francesco-mengarelli",
    role: "Business Development",
    title: "Business Development Manager",
    shortBio: "Sviluppo commerciale e partnership strategiche.",
    email: "francesco.mengarelli@amareacosmetics.it",
    profileUrl: `${site}/team/francesco-mengarelli`
  },
  {
    name: "Dott.ssa Loredana Rao",
    slug: "loredana-rao",
    role: "Regulatory Affairs",
    title: "Consulente Regolatorio Cosmetico",
    shortBio: "Compliance normativa e sicurezza dei prodotti cosmetici.",
    email: "loredana.rao@amareacosmetics.it",
    profileUrl: `${site}/team/loredana-rao`
  },
  {
    name: "Dott.ssa Alida Likey",
    slug: "alida-likey",
    role: "Marketing & Brand",
    title: "Brand & Marketing Strategist",
    shortBio: "Strategia di brand e comunicazione.",
    email: "alida.likey@amareacosmetics.it",
    profileUrl: `${site}/team/alida-likey`
  },
  {
    name: "Avv. Alessandra Marmor\xE8",
    slug: "alessandra-marmore",
    role: "Legal Advisor",
    title: "Avvocato",
    shortBio: "Consulenza legale e societaria.",
    email: "alessandramarmore@outlook.it",
    profileUrl: `${site}/team/alessandra-marmore`
  },
  {
    name: "Prof.ssa Camilla Morresi",
    slug: "camilla-morresi",
    role: "Scientific Advisor",
    title: "Ricercatrice Universitaria",
    shortBio: "Ricerca su composti bioattivi.",
    email: "c.morresi@unilink.it",
    profileUrl: `${site}/team/camilla-morresi`
  },
  {
    name: "Prof.ssa Elisabetta Damiani",
    slug: "elisabetta-damiani",
    role: "Scientific Advisor",
    title: "Professoressa Ordinaria \u2014 Universit\xE0 Politecnica delle Marche",
    shortBio: "Chimica biologica e stress ossidativo.",
    email: "e.damiani@univpm.it",
    profileUrl: `${site}/team/elisabetta-damiani`
  },
  {
    name: "Prof.ssa Tiziana Bacchetti",
    slug: "tiziana-bacchetti",
    role: "Scientific Advisor",
    title: "Professoressa \u2014 Universit\xE0 Politecnica delle Marche",
    shortBio: "Biochimica e nutrizione.",
    email: "t.bacchetti@staff.univpm.it",
    profileUrl: `${site}/team/tiziana-bacchetti`
  }
];
var products = [
  {
    slug: "sibilla",
    name: "Sibilla",
    subtitle: "crema viso anti-aging",
    status: "Prossimamente \u2014 Settembre 2026 (lista prioritaria di lancio aperta)",
    url: `${site}/prodotti/sibilla`
  },
  {
    slug: "conero",
    name: "Conero",
    subtitle: "crema viso purificante",
    status: "In sviluppo",
    url: `${site}/prodotti/conero`
  },
  {
    slug: "catria",
    name: "Catria",
    subtitle: "crema viso idratante",
    status: "In sviluppo",
    url: `${site}/prodotti/catria`
  }
];

// src/lib/mcp/tools/list-team.ts
var list_team_default = defineTool({
  name: "list_team_members",
  title: "List team members",
  description: "Return the Amarea Cosmetics team: name, role, title, short bio, email and profile slug.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(teamMembers, null, 2) }],
    structuredContent: { members: teamMembers }
  })
});

// src/lib/mcp/tools/get-team-member.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var get_team_member_default = defineTool2({
  name: "get_team_member",
  title: "Get team member",
  description: "Return the full profile of a team member by slug (e.g. 'anna-manzella').",
  inputSchema: {
    slug: z.string().min(1).describe("Team member slug, e.g. 'anna-manzella'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const member = teamMembers.find((m) => m.slug === slug);
    if (!member) {
      return {
        content: [{ type: "text", text: `No team member with slug '${slug}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(member, null, 2) }],
      structuredContent: { member }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_products_default = defineTool3({
  name: "list_products",
  title: "List products",
  description: "Return the Amarea Cosmetics product line ('Monti Italiani' collection) with launch status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
    structuredContent: { products }
  })
});

// src/lib/mcp/tools/brand-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var info = {
  name: "Amarea Cosmetics",
  tagline: "Cosmetica biotech, sostenibile e made in Marche.",
  description: "Amarea Cosmetics \xE8 una start-up di cosmetica scientifica nata come spin-off accademico dell'Universit\xE0 Politecnica delle Marche. Valorizziamo bioresidui agroalimentari del territorio marchigiano attraverso l'upcycling, trasformandoli in ingredienti attivi per formulazioni anti-age e sostenibili.",
  headquarters: "Universit\xE0 Politecnica delle Marche, Via Brecce Bianche, Ancona, Italia",
  email: "info@amareacosmetics.com",
  website: "https://amareacosmetics.it",
  values: [
    "Ricerca scientifica",
    "Upcycling e sostenibilit\xE0",
    "Valorizzazione del territorio marchigiano",
    "Cruelty-free"
  ]
};
var brand_info_default = defineTool4({
  name: "get_brand_info",
  title: "Get brand info",
  description: "Return general information about Amarea Cosmetics (mission, contact, values).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
    structuredContent: info
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "amarea-cosmetics-mcp",
  title: "Amarea Cosmetics",
  version: "0.1.0",
  instructions: "Public tools for Amarea Cosmetics: brand info, product line ('Monti Italiani') and team profiles. All data returned is public.",
  tools: [brand_info_default, list_products_default, list_team_default, get_team_member_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
